Repository Roave/DocbookTool, pull requests merged in 2022-03, with the labels that each got.

#20 Ensure graphviz support is enabled, automated dependency upgrades, restructured tests around docker image
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/merge-dependabot-upgrades.yml
  .github/workflows/phpcs.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/publish-docker-image-to-github-registry.yml
  Dockerfile
  package-lock.json
  package.json
  phpunit.xml.dist
Labels: enhancement

#41 Upgraded dependencies and core PHP version to be on PHP 8.1.3+
  Dockerfile
  composer.json
  composer.lock
  src/Environment.php
  src/Formatter/ExtractFrontMatter.php
  src/Formatter/RenderPlantUmlDiagramInline.php
  src/InteractiveHttpBasicAuthTokenCreator.php
  src/Writer/ConfluenceWriter.php
  src/Writer/MultiplePdfFilesWriter.php
Labels: enhancement, dependencies, php

#21 Install `wkhtmltopdf` via `apt`, leveraging `ubuntu:20.04` multi-arch base image support
  Dockerfile
Labels: enhancement

#46 Use fully qualified tags for good hygeine
  .github/workflows/ci.yml
  Makefile
Labels: enhancement

#47 Dockerfile bikeshedding
  Dockerfile
  Makefile
Labels: enhancement

#48 Reduce image size by not installing apt recommended packages
  Dockerfile
Labels: enhancement, dependencies

#49 Publish docker tags for major/minor
  .github/workflows/publish-docker-image-to-github-registry.yml
Labels: enhancement

#55 Fix Dockerfile composer bind mounts
  Dockerfile
Labels: bug

#65 Cache CI build to GHA
  .github/workflows/ci.yml
  .github/workflows/publish-docker-image-to-github-registry.yml
Labels: enhancement

#66 Cache apt activity
  Dockerfile
Labels: enhancement

#59 Remove rw flag from composer.lock mount
  Dockerfile
Labels: enhancement, dependencies
