Repository Roave/DocbookTool, pull requests merged in 2024-03, with the labels that each got.

#372 Support larger inline images
  src/Formatter/MarkdownToHtml.php
  test/fixture/docbook/large-image.jpeg
  test/fixture/docbook/test.md
  test/fixture/expectations/out.html
Labels: bug

#373 Add internal CSS styles
  README.md
  css/internal-html-styles.css
  css/internal-pdf-styles.css
Labels: documentation

#375 Fix the path that is used for src-json tag
  README.md
Labels: bug, documentation
